# This workflow is the entry point for all CI processes.
# It is from here that all other workflows are launched.
name: Orbiter installable app

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'renovate/**'
    tags:
      - v*
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/typechecking.yml'
      - '!.github/workflows/tests.yml'
      - '!.github/workflows/webTests.yml'
      - '!.github/workflows/release.yml'
      - '!.github/workflows/publishPage.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '!.github/workflows/typechecking.yml'
      - '!.github/workflows/tests.yml'
      - '!.github/workflows/webtests.yml'
      - '!.github/workflows/release.yml'
      - '!.github/workflows/publishPage.yml'
      - '**.md'
      - .editorconfig
      - .gitignore
      - '.idea/**'
      - '.vscode/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typechecking:
    uses: ./.github/workflows/typechecking.yml
  tests:
    uses: ./.github/workflows/tests.yml
  tests_navig:
    uses: ./.github/workflows/webTests.yml
  publier_appli_internet:
    needs: [ typechecking, web_tests ]
    uses: ./.github/workflows/publishPage.yml
  draft_release:
    permissions:
      contents: write # Allows this job to create releases
    with:
      dry-run: ${{ github.event_name != 'push' || github.ref_name != 'main' }}
    needs: [ typechecking, tests ]
    uses: ./.github/workflows/release.yml
